name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 4" # every Thursday

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read

jobs:
  rspec:
    uses: solidusio/test-solidus-extension/.github/workflows/test.yml@main
    with:
      ruby_versions: '["3.4"]'
      rails_versions: '["8.0", "7.2"]'
      solidus_branches: '["v4.7"]'
      databases: '["postgresql", "sqlite"]'
